server:
  # 端口
  port: 8081

spring:
  application:
    # 应用名
    name: multi-datasource-service
  datasource:
    # dynamic-datasource-spring-boot-starter 动态数据源的配配项，对应 DynamicDataSourceProperties 类
    dynamic:
      # 设置默认的数据源或者数据源组，默认值即为 master
      primary: order-ds
      datasource:
        # 订单 order 数据源配置
        order-ds:
          url: jdbc:mysql://106.53.217.86:3306/seata_order?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: Lzx1922026241@
        # 账户pay数据源配置
        account-ds:
          url: jdbc:mysql://106.53.217.86:3306/seata_account?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: Lzx1922026241@
        # 商品product数据源配置
        product-ds:
          url: jdbc:mysql://106.53.217.86:3306/seata_product?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: Lzx1922026241@
      # 是否启动对 Seata 的集成
      seata: true

# Seata 配置项，对应SeataProperties类
seata:
  application-id: ${spring.application.name} # Seata应用编号，默认为 ${spring.application.name}
  tx-service-group: ${spring.application.name}-group # Seata 事务组编号，用于TC集群名
  #服务配置项，对应 ServiceProperties 类
  service:
    #虚拟组和分组的映射
    vgroup-mapping:
      multi-datasource-service-group: default
    #分组和Seata服务的映射
    grouplist:
      default: 127.0.0.1:8091

# mybatis
mybatis-plus:
  typeAliasesPackage: com.lzx.seata.multiple.data.source.entity
  global-config:
    db-config:
      id-type: AUTO
      capital-mode: true
      logic-delete-value: -1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl