server:
  port: 8082

spring:
  application:
    name: spring-cloud-product-server
  datasource:
    url: jdbc:mysql://106.53.217.86:3306/seata_product?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lzx1922026241@

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka

seata:
  # Seata 应用编号，默认为 ${spring.application.name}
  application-id: ${spring.application.name}
  # Seata 事务组编号，用于 TC 集群名
  tx-service-group: ${spring.application.name}-group
  # Seata 服务配置项，对应 ServiceProperties 类
  service:
    # 虚拟组和分组的映射
    vgroup-mapping:
      spring-cloud-product-server-group: default
  # 第一种方式，注册中心连tc，Seata 注册中心配置项，对应 RegistryProperties 类
  registry:
    type: eureka # 注册中心类型，默认为 file
    eureka:
      application: default
      service-url: http://127.0.0.1:8080/eureka
    # 第二种方式，分组和 Seata 服务的映射（直接连tc）
      #grouplist:
      #default: 106.53.217.86:8091


logging:
  level:
    com:
      lzx: info

# mybatis
mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
      capital-mode: true
      logic-delete-value: -1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl